version: '3.9'
services:
  web:
    container_name: 'node'
    image: 'node:18'
    working_dir: '/usr/app'
    build: .
    command: "bash -c 'yarn && yarn dev'"
    volumes:
      - .:/usr/app
      - ./node_modules:/usr/app/node_modules
    ports: 
      - "${NODE_HOST_PORT}:${NODE_CONTAINER_PORT}"
    depends_on:
      - postgres
  postgres:
    container_name: 'postgres'
    image: 'postgres:15'
    hostname: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    expose:
      - "5432"
    ports:
      - "5432:5432"
volumes:
  postgres-data:
    